@startuml
hide footbox
participant "Controller : c"
participant "Modele : m"
participant "Observateur : o"

"Controller : c" -> "Modele : m" : logger(message)
activate "Modele : m"

"Modele : m" -> "Modele : m" : log = message
"Modele : m" -> "Modele : m" : notifierObservateurs()

loop pour chaque "Observateur : o"
    "Modele : m" -> "Observateur : o" : actualiser(this)
end

deactivate "Modele : m"
@enduml
