@startuml

title Diagramme de classe global - TouDou

/'
#########################
PATRON D'ARCHITECTURE MVC
#########################
'/

package Modèle {

    interface Sujet {
        + {abstract} ajouterObservateur(Observateur)
        + {abstract} retirerObservateur(Observateur)
        + {abstract} notifierObservateurs()
    }

    class Modele {
        + ajouterObservateur(Observateur)
        + retirerObservateur(Observateur)
        + notifierObservateurs()
        + ajouterColonne(Colonne)
    }

    class Colonne {
        - nomColonne
    }

    class FabriqueTache {
        + creerTache(nom, description, dateEcheance, tempsNecessaire) : Tache
        + creerSousTache(nom, description) : Tache
    }

    class Tache {
        - numTache
        - nom
        - description
        - dateEcheance
        - tempsNecessaire
        - archive : [VRAI/FAUX]
        + archiverTache()
        + {static} create(nom, desc, dateEcheance, tempsNecessaire) : Tache
        + {static} read(numTache) : Tache
        + update()
        + delete()
    }

    class SousTache {
        - numSousTache
        - nom
        - description
    }

    class Couleur {
        - couleurPrimaire
        - couleurSecondaire
    }

    /'
    ###########
    DEPENDANCES
    ###########
    '/
    Sujet <|.. Modele
    Modele "*" -> "1" Colonne : - colonnes
    Colonne "*" --> "1" Couleur : - couleur
    Colonne "*" --> "1" Tache : - taches
    Tache "*" --> "*" SousTache : - sousTaches
    Tache "*" -> "*" Tache : - dependances
    FabriqueTache ..> Tache : create
    FabriqueTache ..> SousTache : create

    /'
    ####################
    PATRON ACTIVE RECORD
    ####################
    '/
    package ActiveRecord {

        class DBConnection {
            - {static} instance
            - connection
            - username
            - password
            - serverName
            - portNumber
            - dbName
            - DBConnection(username, password, serverName, portNumber, dbName)
            + {static} getInstance()
            + getConnection()
            + setNomDB(nomDB)
        }

    }


    Tache ..> DBConnection : use

}

package Vue {

    interface Observateur {
        + {abstract} actualiser(Sujet)
    }

    class VueBureau {
        + actualiser(Sujet)
    }

    class VueListe {
        + actualiser(Sujet)
    }

    class VueGantt {
        + actualiser(Sujet)
    }

    class VueHistorique {
        + actualiser(Sujet)
    }

    /'
    ###########
    DEPENDANCES
    ###########
    '/
    Observateur <|.. VueBureau
    Observateur <|.. VueListe
    Observateur <|.. VueGantt
    Observateur <|.. VueHistorique
    VueBureau "*" <-- "1" Modele : - modele
    VueListe "*" <-- "1" Modele : - modele
    VueGantt "*" <-- "1" Modele : - modele
    VueHistorique "*" <-- "1" Modele : - modele

}

package Controlleur {

    interface EventHandler<ActionEvent> {
        + {abstract} handle(ActionEvent event)
    }

    class ControlBtnAddTache {
        + handle(ActionEvent event)
    }

    class ControlBtnSupprTache {
        + handle(ActionEvent event)
    }

    class ControlBtnGanttOptions {
        + handle(ActionEvent event)
    }

    class ControlBtnArchives {
        + handle(ActionEvent event)
    }

    class ControlBtnGanttGenerer {
        + handle(ActionEvent event)
    }

    /'
    ###########
    DEPENDANCES
    ###########
    '/
    EventHandler <|.. ControlBtnAddTache
    EventHandler <|.. ControlBtnSupprTache
    EventHandler <|.. ControlBtnGanttOptions
    EventHandler <|.. ControlBtnArchives
    EventHandler <|.. ControlBtnGanttGenerer
    ControlBtnAddTache "*" <-- "1" Modele : - modele
    ControlBtnSupprTache "*" <-- "1" Modele : - modele
    ControlBtnGanttOptions "*" <-- "1" Modele : - modele
    ControlBtnArchives "*" <-- "1" Modele : - modele
    ControlBtnGanttGenerer "*" <-- "1" Modele : - modele

}



/'
##########################
DEPENDANCES ENTRE PACKAGES
##########################
'/
Modele "*" --> "*" Observateur : - observateurs





/'
###########################
TOUS LES PATRONS UTILISES :
###########################

- MVC : identifié par package
- Active Record : accès à BDD, CRUD -> Create, Read, Update, Delete

- Observateur : en lien avec MVC
- Composite : gestion des tâches dépendantes
- Fabrique : création de tâches et de sous-tâches
- Singleton : pour avoir une unique instance du driver de BDD

'/

@enduml